//! What a box is, and which set of rules lays its children out.

/// The rules a box lays its children out by.
///
/// This is decided once, when the box is built, so that the layout pass is a match on a tag rather
/// than a re-reading of `display` at every step — and so that the boxes a `display` value implies
/// but does not name, such as the anonymous box wrapping a run of inline siblings, can carry a
/// context of their own.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum FormattingContext {
    /// Generates no box geometry at all: the subtree is laid out at zero size and skipped.
    None,
    /// Block flow: children stack down the block axis, vertical margins collapse, floats apply.
    Block,
    /// Flex layout.
    Flex,
    /// Grid layout.
    Grid,
    /// An inline formatting context: a run of text and inline boxes broken into lines.
    Inline,
    /// A replaced element, sized from the intrinsic size of content this engine does not own.
    Replaced,
    /// An atomic inline — `inline-block`, `inline-flex`, `inline-grid` — which is a leaf to the
    /// context around it and a container to the one inside it.
    Atomic,
    /// Table layout.
    Table,
    /// Multi-column layout.
    MultiColumn,
}

impl FormattingContext {
    /// A short, stable name, for tree dumps and diagnostics.
    pub const fn label(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Block => "block",
            Self::Flex => "flex",
            Self::Grid => "grid",
            Self::Inline => "inline",
            Self::Replaced => "replaced",
            Self::Atomic => "atomic",
            Self::Table => "table",
            Self::MultiColumn => "multicol",
        }
    }

    /// Whether this context lays its children out itself rather than measuring its content.
    ///
    /// The three that do not — inline, replaced and atomic content — are the ones that reach the
    /// leaf path, where the size comes from a measurement rather than from an algorithm.
    pub const fn is_container(self) -> bool {
        matches!(self, Self::Block | Self::Flex | Self::Grid)
    }
}

/// Where a box came from.
///
/// Only [`BoxKind::Element`] corresponds one-to-one with something an author wrote. The rest are
/// boxes CSS requires but no element names: the wrappers that keep a mixed container's children
/// all block-level or all inline-level, the text between the elements, and a list item's mark.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BoxKind {
    /// A box generated by an element or by one of its generated-content pseudo-elements.
    Element,
    /// An anonymous block box wrapping the block-level children of a container that also has
    /// inline-level ones.
    AnonymousBlock,
    /// An anonymous box wrapping a maximal run of inline-level siblings, which is what an inline
    /// formatting context is established on.
    AnonymousInlineRoot,
    /// A run of text.
    TextRun,
    /// A list item's mark.
    Marker,
}

impl BoxKind {
    /// A short, stable name, for tree dumps and diagnostics.
    pub const fn label(self) -> &'static str {
        match self {
            Self::Element => "element",
            Self::AnonymousBlock => "anon-block",
            Self::AnonymousInlineRoot => "anon-inline-root",
            Self::TextRun => "text",
            Self::Marker => "marker",
        }
    }

    /// Whether this box has no element of its own and takes a synthesised style.
    pub const fn is_anonymous(self) -> bool {
        matches!(
            self,
            Self::AnonymousBlock | Self::AnonymousInlineRoot | Self::TextRun | Self::Marker
        )
    }
}

/// Which generated-content pseudo-element a box realises.
///
/// This crate is the type's only home: no node carries it, because a pseudo-element has no node of
/// its own. A box carrying it names the element it was generated *from*, so a click on it, its
/// accessible geometry and its ancestor chain all resolve to that element and nothing downstream
/// needs a special case.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PseudoKind {
    /// The box placed before the originating element's own content.
    Before,
    /// The box placed after it.
    After,
}

impl PseudoKind {
    /// A short, stable name, for tree dumps and diagnostics.
    pub const fn label(self) -> &'static str {
        match self {
            Self::Before => "before",
            Self::After => "after",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{BoxKind, FormattingContext, PseudoKind};

    #[test]
    fn only_the_element_box_is_not_anonymous() {
        assert!(!BoxKind::Element.is_anonymous());
        for kind in [
            BoxKind::AnonymousBlock,
            BoxKind::AnonymousInlineRoot,
            BoxKind::TextRun,
            BoxKind::Marker,
        ] {
            assert!(kind.is_anonymous(), "{kind:?}");
        }
    }

    #[test]
    fn the_measured_contexts_are_not_containers() {
        for context in [
            FormattingContext::Inline,
            FormattingContext::Replaced,
            FormattingContext::Atomic,
        ] {
            assert!(!context.is_container(), "{context:?}");
        }
        for context in [
            FormattingContext::Block,
            FormattingContext::Flex,
            FormattingContext::Grid,
        ] {
            assert!(context.is_container(), "{context:?}");
        }
    }

    #[test]
    fn every_label_is_distinct() {
        let mut labels: Vec<&str> = [
            FormattingContext::None,
            FormattingContext::Block,
            FormattingContext::Flex,
            FormattingContext::Grid,
            FormattingContext::Inline,
            FormattingContext::Replaced,
            FormattingContext::Atomic,
            FormattingContext::Table,
            FormattingContext::MultiColumn,
        ]
        .iter()
        .map(|context| context.label())
        .chain(
            [
                BoxKind::Element,
                BoxKind::AnonymousBlock,
                BoxKind::AnonymousInlineRoot,
                BoxKind::TextRun,
                BoxKind::Marker,
            ]
            .iter()
            .map(|kind| kind.label()),
        )
        .chain(
            [PseudoKind::Before, PseudoKind::After]
                .iter()
                .map(|pseudo| pseudo.label()),
        )
        .collect();
        let count = labels.len();
        labels.sort_unstable();
        labels.dedup();
        assert_eq!(labels.len(), count, "a dump has to tell these apart");
    }
}
