//! Splicing one element's boxes into a box tree that is already there.
//!
//! Two claims, and neither is worth anything without the other. **The work is local** — only the
//! marked element's own container has its boxes made again, and every other box in the document
//! keeps the name it had, because a box's name is what fragment reuse, geometry diffing and damage
//! scissoring are all keyed on. **The result is the same** — the tree left behind renders exactly
//! the bytes a build from the document root renders, so being cheaper has not made it different.
//!
//! Every case holds a counter recording, even the ones that assert nothing about a counter. The
//! counters are one process-wide block, so a build running on another thread of this same binary
//! would land in whatever measurement happened to be open — and the recording is what serialises
//! them.
//!
//! The refusals are tested as hard as the splices. A splice that cannot prove a subtree is confined
//! has to say so and let the caller build the whole tree, and a refusal that stopped happening
//! would show up nowhere else: the tree would be quietly wrong in a way only a dangling key or a
//! missing anonymous wrapper reveals, several frames later.

mod support;

use support::{Element, Fixture};
use zgui_dom::side::BoxKey;
use zgui_dom::{NodeIndex, NodeKind};
use zgui_layout::boxtree::Owed;
use zgui_layout::boxtree::patch;
use zgui_layout::tree::print::to_text;
use zgui_layout::tree::store::LayoutStore;
use zgui_profile::Counter;
use zgui_testkit_scene::counters::Recording;

/// The element named `name`, which every fixture below gives a distinct name.
///
/// # Panics
///
/// Panics when nothing in the document carries the name, because the caller is about to assert
/// something about it and `None` would make that assertion pass by never running.
fn element(fixture: &Fixture, name: &str) -> NodeIndex {
    let store = fixture.document.store();
    let mut stack = vec![fixture.root];
    while let Some(index) = stack.pop() {
        if store.core(index).kind() == NodeKind::Element
            && store.core(index).local_name().as_str() == name
        {
            return index;
        }
        let mut next = store.core(index).first_child();
        while let Some(child) = next {
            stack.push(child);
            next = store.core(child).next_sibling();
        }
    }
    panic!("the fixture has no `{name}` element");
}

/// A tree rendering with the box numbers taken out of it.
///
/// The rendering names a box only where the two child orders differ, and there by its position in
/// the arena — which is exactly what a splice changes and what nothing downstream reads. Comparing
/// the renderings verbatim would therefore compare allocation order; comparing them with the
/// numbers replaced keeps the claim (these two boxes hang in different orders here) and drops the
/// identity.
fn shape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(at) = rest.find("paint-order=[") {
        out.push_str(&rest[..at]);
        out.push_str("paint-order=[..]");
        let after = &rest[at..];
        let end = after.find(']').map_or(after.len(), |index| index + 1);
        rest = &after[end..];
    }
    out.push_str(rest);
    out
}

/// The boxes one element generated, by name.
fn boxes(store: &LayoutStore, fixture: &Fixture, name: &str) -> Vec<BoxKey> {
    let key = fixture.document.store().key_of(element(fixture, name));
    store.boxes_of(key).to_vec()
}

/// How many boxes at or below `root` were built from an element, in either child order.
///
/// Which is what [`Counter::BoxesRebuilt`] counts: an anonymous wrapper is required by the
/// formatting context around a run rather than generated by anything in the document, so the
/// builder makes one without recording it as a box an element owes.
fn under(store: &LayoutStore, root: BoxKey) -> u64 {
    let mut seen = std::collections::BTreeSet::new();
    let mut stack = vec![root];
    while let Some(key) = stack.pop() {
        if !seen.insert(key) {
            continue;
        }
        let Some(node) = store.get(key) else {
            continue;
        };
        stack.extend(node.children.iter().copied());
        stack.extend(node.paint_children.iter().copied());
    }
    seen.into_iter()
        .filter(|&key| store.get(key).is_some_and(|node| node.source.is_some()))
        .count() as u64
}

/// The obligation one element's own boxes owe.
fn owes_boxes(index: NodeIndex) -> Owed {
    Owed {
        rebuilt: vec![index],
        children: Vec::new(),
    }
}

/// Two panels side by side, each holding one block with text in it.
fn two_panels(css: &str) -> Fixture {
    Fixture::new(
        Element::new("root").children(vec![
            Element::new("left").children(vec![Element::new("first").text("one")]),
            Element::new("right").children(vec![Element::new("second").text("two")]),
        ]),
        css,
    )
}

/// The ordinary shape: every element a block, nothing positioned, nothing inline.
const BLOCKS: &str = "root { display: block; width: 400px }
                      left, right, first, second { display: block }";

#[test]
fn a_local_structural_change_rebuilds_only_its_own_subtree() {
    let mut recording = Recording::begin();
    let fixture = two_panels(BLOCKS);
    let mut store = fixture.box_tree();

    let untouched = boxes(&store, &fixture, "right");
    let replaced = boxes(&store, &fixture, "left");
    let root = store.root().expect("the fixture generates a tree");
    let total = under(&store, root);

    // The control. Building the tree rebuilds every box in it, which is what makes the bound below
    // mean "this splice did not" rather than "nothing here ever counts a box".
    let built = recording.measure(|| {
        let _ = fixture.box_tree();
    });
    assert_eq!(
        built.get(Counter::BoxesRebuilt),
        total,
        "the control did not build the whole document"
    );

    // `first` is the element whose own boxes changed, so what is rebuilt is `left`: how a child is
    // wrapped, ordered and blockified is its container's decision.
    let spliced = recording.measure(|| {
        let done = patch::rebuild(
            &mut store,
            &fixture.document,
            &owes_boxes(element(&fixture, "first")),
        )
        .expect("a block inside a block is confined");
        assert_eq!(done.subtrees, 1, "one container was rebuilt");
    });

    let left = boxes(&store, &fixture, "left");
    let left_box = left.first().copied().expect("`left` generates a box");
    assert_eq!(
        spliced.get(Counter::BoxesRebuilt),
        under(&store, left_box),
        "the splice built something other than exactly the marked container's own subtree"
    );
    assert!(
        spliced.get(Counter::BoxesRebuilt) < total,
        "the splice rebuilt the whole document, which is the defect it exists to remove"
    );

    assert_eq!(
        boxes(&store, &fixture, "right"),
        untouched,
        "a panel nothing marked was given new boxes, so every fragment in it compares as changed"
    );
    assert_eq!(
        store.root(),
        Some(root),
        "the document's root box was replaced by a splice three levels below it"
    );
    assert_ne!(
        left, replaced,
        "the marked container's boxes are the new ones"
    );

    // And the cheaper answer is the same answer.
    assert_eq!(
        shape(&to_text(&store)),
        shape(&to_text(&fixture.box_tree())),
        "the spliced tree is not the tree a build from the root produces"
    );
}

#[test]
fn a_container_that_gained_a_child_is_the_container_that_is_rebuilt() {
    let _recording = Recording::begin();
    let mut fixture = two_panels(BLOCKS);
    let mut store = fixture.box_tree();
    let untouched = boxes(&store, &fixture, "right");

    let left = element(&fixture, "left");
    fixture.edit_and_restyle(|edit| {
        let child = edit.create_element(zgui_interned::ElementName::new("first"));
        let text = edit.create_text("three");
        edit.insert_before(child, text, None);
        edit.insert_before(left, child, None);
    });

    let owed = Owed {
        rebuilt: Vec::new(),
        children: vec![left],
    };
    let done = patch::rebuild(&mut store, &fixture.document, &owed)
        .expect("appending into a block container is confined");
    assert_eq!(done.subtrees, 1);
    assert_eq!(
        boxes(&store, &fixture, "right"),
        untouched,
        "the sibling panel was rebuilt for a child that was added to the other one"
    );
    assert_eq!(
        shape(&to_text(&store)),
        shape(&to_text(&fixture.box_tree())),
        "the spliced tree does not hold the child that was appended"
    );
}

#[test]
fn a_box_positioned_from_outside_the_subtree_refuses_the_splice() {
    let _recording = Recording::begin();
    // `first` is absolutely positioned against `root`, so its box is a layout child of `root` and a
    // paint child of `left`. Replacing `left` would destroy a box that `root`'s child list still
    // names, and nothing in `left` would ever notice.
    let fixture = two_panels(
        "root { display: block; width: 400px; position: relative }
         left, right, second { display: block }
         first { display: block; position: absolute; top: 0; left: 0 }",
    );
    let mut store = fixture.box_tree();
    let before = shape(&to_text(&store));

    assert!(
        patch::rebuild(
            &mut store,
            &fixture.document,
            &owes_boxes(element(&fixture, "first"))
        )
        .is_none(),
        "a subtree holding a box its own container does not lay out was spliced anyway"
    );
    assert_eq!(
        shape(&to_text(&store)),
        before,
        "a refused splice left the tree changed"
    );
}

#[test]
fn a_container_that_stops_generating_a_box_refuses_rather_than_leaving_a_hole() {
    let _recording = Recording::begin();
    // `left` is what would be replaced, and the change makes it generate nothing. The splice may
    // take it out only where doing so cannot re-wrap what is left; `root` here holds two blocks and
    // no inline run, so it may — and the tree that results is the tree a build produces.
    let mut fixture = two_panels(
        "root { display: block; width: 400px }
         left, right, first, second { display: block }
         .away { display: none }",
    );
    let mut store = fixture.box_tree();
    let left = element(&fixture, "left");
    fixture.edit_and_restyle(|edit| {
        edit.set_classes(left, &[zgui_interned::ClassName::new("away")]);
    });

    let done = patch::rebuild(
        &mut store,
        &fixture.document,
        &owes_boxes(element(&fixture, "first")),
    )
    .expect("removing one block from a container of blocks is confined");
    assert!(done.removed > 0, "nothing was taken out of the tree");
    assert_eq!(
        shape(&to_text(&store)),
        shape(&to_text(&fixture.box_tree())),
        "the tree left after the removal is not the tree a build produces"
    );
}

#[test]
fn a_child_that_changes_from_block_level_to_inline_level_refuses_the_splice() {
    let _recording = Recording::begin();
    // What would be replaced is `left`, and `left` becoming inline-level changes how *`right`* is
    // wrapped: a container with one inline child and one block child wraps the inline one in an
    // anonymous box that does not exist while both are blocks. `right` carries no mark, so a splice
    // that went ahead would leave the wrapping the old tree had.
    let mut fixture = two_panels(
        "root { display: block; width: 400px }
         left, right, first, second { display: block }
         .inline { display: inline }",
    );
    let mut store = fixture.box_tree();
    let left = element(&fixture, "left");
    fixture.edit_and_restyle(|edit| {
        edit.set_classes(left, &[zgui_interned::ClassName::new("inline")]);
    });
    let before = shape(&to_text(&store));

    assert!(
        patch::rebuild(
            &mut store,
            &fixture.document,
            &owes_boxes(element(&fixture, "first"))
        )
        .is_none(),
        "a box that changed how its siblings are wrapped was spliced in beside them"
    );
    assert_eq!(
        shape(&to_text(&store)),
        before,
        "a refused splice left the tree changed, so the build that follows starts from a tree \
         that is neither the old one nor the new one"
    );
}

#[test]
fn the_root_element_has_no_container_to_splice_it_into() {
    let _recording = Recording::begin();
    let fixture = two_panels(BLOCKS);
    let mut store = fixture.box_tree();
    assert!(
        patch::rebuild(&mut store, &fixture.document, &owes_boxes(fixture.root)).is_none(),
        "the root element's container is the document node, which generates no box"
    );
}
