//! Probes for the properties that decide where a box is and how big it is.
//!
//! Each row names one longhand and a declaration that sets it to something other than its
//! initial value. The declaration is data, not a claim: what it is for is to be applied to a
//! fixture so that the framework can be asked whether anything downstream noticed.

use crate::evidence::probe::Probe;

/// One probe per longhand in this group.
pub static PROBES: &[Probe] = &[
    Probe::new("align_content", "align-content: space-between"),
    Probe::new("align_items", "align-items: flex-end"),
    Probe::new("align_self", "align-self: flex-end"),
    Probe::new("alignment_baseline", "alignment-baseline: middle"),
    Probe::new("aspect_ratio", "aspect-ratio: 2 / 1"),
    Probe::new("backface_visibility", "backface-visibility: hidden"),
    Probe::new("baseline_shift", "baseline-shift: 5px"),
    Probe::new("baseline_source", "baseline-source: last"),
    Probe::new("block_size", "block-size: 37px"),
    Probe::new("border_collapse", "border-collapse: collapse"),
    Probe::new("border_spacing", "border-spacing: 5px"),
    Probe::new("bottom", "bottom: 11px"),
    Probe::new("box_sizing", "box-sizing: content-box"),
    Probe::new("caption_side", "caption-side: bottom"),
    Probe::new("clear", "clear: left"),
    Probe::new("column_count", "column-count: 3"),
    Probe::new("column_gap", "column-gap: 12px"),
    Probe::new("column_span", "column-span: all"),
    Probe::new("column_width", "column-width: 40px"),
    Probe::new("contain", "contain: layout"),
    Probe::new("container_name", "container-name: panel"),
    Probe::new("container_type", "container-type: inline-size"),
    Probe::new("display", "display: inline-block"),
    Probe::new("empty_cells", "empty-cells: hide"),
    Probe::new("flex_basis", "flex-basis: 23px"),
    Probe::new("flex_direction", "flex-direction: column"),
    Probe::new("flex_grow", "flex-grow: 2"),
    Probe::new("flex_shrink", "flex-shrink: 0"),
    Probe::new("flex_wrap", "flex-wrap: nowrap"),
    Probe::new("float", "float: left"),
    Probe::new("grid_auto_columns", "grid-auto-columns: 50px"),
    Probe::new("grid_auto_flow", "grid-auto-flow: column"),
    Probe::new("grid_auto_rows", "grid-auto-rows: 50px"),
    Probe::new("grid_column_end", "grid-column-end: 3"),
    Probe::new("grid_column_start", "grid-column-start: 2"),
    Probe::new("grid_row_end", "grid-row-end: 3"),
    Probe::new("grid_row_start", "grid-row-start: 2"),
    Probe::new("grid_template_areas", r#"grid-template-areas: "a b""#),
    Probe::new("grid_template_columns", "grid-template-columns: 30px 70px"),
    Probe::new("grid_template_rows", "grid-template-rows: 30px 70px"),
    Probe::new("height", "height: 44px"),
    Probe::new("inline_size", "inline-size: 37px"),
    Probe::new("inset_block_end", "inset-block-end: 11px"),
    Probe::new("inset_block_start", "inset-block-start: 11px"),
    Probe::new("inset_inline_end", "inset-inline-end: 11px"),
    Probe::new("inset_inline_start", "inset-inline-start: 11px"),
    Probe::new("isolation", "isolation: isolate"),
    Probe::new("justify_content", "justify-content: space-between"),
    Probe::new("justify_items", "justify-items: end"),
    Probe::new("justify_self", "justify-self: end"),
    Probe::new("left", "left: 11px"),
    Probe::new("margin_block_end", "margin-block-end: 11px"),
    Probe::new("margin_block_start", "margin-block-start: 11px"),
    Probe::new("margin_bottom", "margin-bottom: 11px"),
    Probe::new("margin_inline_end", "margin-inline-end: 11px"),
    Probe::new("margin_inline_start", "margin-inline-start: 11px"),
    Probe::new("margin_left", "margin-left: 11px"),
    Probe::new("margin_right", "margin-right: 11px"),
    Probe::new("margin_top", "margin-top: 11px"),
    Probe::new("max_block_size", "max-block-size: 21px"),
    Probe::new("max_height", "max-height: 21px"),
    Probe::new("max_inline_size", "max-inline-size: 21px"),
    Probe::new("max_width", "max-width: 21px"),
    Probe::new("min_block_size", "min-block-size: 190px"),
    Probe::new("min_height", "min-height: 190px"),
    Probe::new("min_inline_size", "min-inline-size: 190px"),
    Probe::new("min_width", "min-width: 190px"),
    Probe::new("object_fit", "object-fit: contain"),
    Probe::new("object_position", "object-position: 10px 20px"),
    Probe::new("offset_path", r#"offset-path: path("M 0 0 H 10")"#),
    Probe::new("order", "order: 2"),
    Probe::new("overflow_block", "overflow-block: scroll"),
    Probe::new("overflow_clip_margin", "overflow-clip-margin: 5px"),
    Probe::new("overflow_inline", "overflow-inline: scroll"),
    Probe::new("overflow_x", "overflow-x: scroll"),
    Probe::new("overflow_y", "overflow-y: scroll"),
    Probe::new("padding_block_end", "padding-block-end: 11px"),
    Probe::new("padding_block_start", "padding-block-start: 11px"),
    Probe::new("padding_bottom", "padding-bottom: 11px"),
    Probe::new("padding_inline_end", "padding-inline-end: 11px"),
    Probe::new("padding_inline_start", "padding-inline-start: 11px"),
    Probe::new("padding_left", "padding-left: 11px"),
    Probe::new("padding_right", "padding-right: 11px"),
    Probe::new("padding_top", "padding-top: 11px"),
    Probe::new("perspective", "perspective: 500px"),
    Probe::new("perspective_origin", "perspective-origin: 10px 20px"),
    Probe::new("position", "position: absolute"),
    Probe::new("position_area", "position-area: top left"),
    Probe::new(
        "position_try_fallbacks",
        "position-try-fallbacks: flip-block",
    ),
    Probe::new("right", "right: 11px"),
    Probe::new("rotate", "rotate: 90deg"),
    Probe::new("row_gap", "row-gap: 12px"),
    Probe::new("scale", "scale: 2"),
    Probe::new("table_layout", "table-layout: fixed"),
    Probe::new("top", "top: 11px"),
    Probe::new("transform", "transform: translate(11px, 13px)"),
    Probe::new("transform_origin", "transform-origin: 10px 20px"),
    Probe::new("transform_style", "transform-style: preserve-3d"),
    Probe::new("translate", "translate: 11px 13px"),
    Probe::new("width", "width: 44px"),
    Probe::new("will_change", "will-change: transform"),
    Probe::new("z_index", "z-index: 3"),
];
