//! The properties every layout mode reads: what box an element generates, how big it is, where
//! it sits and what surrounds its content.
//!
//! Every row here is evidence-backed: setting the property on a fixture changes the fragment
//! tree or the answer hit testing gives, and a row whose probe stops showing that fails.

use zgui_css::parity::Support;

/// Where these properties are read.
const READER: &str = "zgui-layout::style::core";

zgui_css::register_properties! {
    aspect_ratio => Support::Implemented(READER),
    block_size => Support::Implemented(READER),
    border_block_end_style => Support::Implemented(READER),
    border_block_end_width => Support::Implemented(READER),
    border_block_start_style => Support::Implemented(READER),
    border_block_start_width => Support::Implemented(READER),
    border_bottom_style => Support::Implemented(READER),
    border_bottom_width => Support::Implemented(READER),
    border_inline_end_style => Support::Implemented(READER),
    border_inline_end_width => Support::Implemented(READER),
    border_inline_start_style => Support::Implemented(READER),
    border_inline_start_width => Support::Implemented(READER),
    border_left_style => Support::Implemented(READER),
    border_left_width => Support::Implemented(READER),
    border_right_style => Support::Implemented(READER),
    border_right_width => Support::Implemented(READER),
    border_top_style => Support::Implemented(READER),
    border_top_width => Support::Implemented(READER),
    bottom => Support::Implemented(READER),
    box_sizing => Support::Implemented(READER),
    clear => Support::Implemented(READER),
    content => Support::Implemented(READER),
    display => Support::Implemented(READER),
    float => Support::Implemented(READER),
    height => Support::Implemented(READER),
    inline_size => Support::Implemented(READER),
    inset_block_end => Support::Implemented(READER),
    inset_block_start => Support::Implemented(READER),
    inset_inline_end => Support::Implemented(READER),
    inset_inline_start => Support::Implemented(READER),
    left => Support::Implemented(READER),
    margin_block_end => Support::Implemented(READER),
    margin_block_start => Support::Implemented(READER),
    margin_bottom => Support::Implemented(READER),
    margin_inline_end => Support::Implemented(READER),
    margin_inline_start => Support::Implemented(READER),
    margin_left => Support::Implemented(READER),
    margin_right => Support::Implemented(READER),
    margin_top => Support::Implemented(READER),
    max_block_size => Support::Implemented(READER),
    max_height => Support::Implemented(READER),
    max_inline_size => Support::Implemented(READER),
    max_width => Support::Implemented(READER),
    min_block_size => Support::Implemented(READER),
    min_height => Support::Implemented(READER),
    min_inline_size => Support::Implemented(READER),
    min_width => Support::Implemented(READER),
    overflow_block => Support::Implemented(READER),
    overflow_inline => Support::Implemented(READER),
    overflow_x => Support::Implemented(READER),
    overflow_y => Support::Implemented(READER),
    padding_block_end => Support::Implemented(READER),
    padding_block_start => Support::Implemented(READER),
    padding_bottom => Support::Implemented(READER),
    padding_inline_end => Support::Implemented(READER),
    padding_inline_start => Support::Implemented(READER),
    padding_left => Support::Implemented(READER),
    padding_right => Support::Implemented(READER),
    padding_top => Support::Implemented(READER),
    position => Support::Implemented(READER),
    right => Support::Implemented(READER),
    top => Support::Implemented(READER),
    width => Support::Implemented(READER),
}
