//! A custom element keeps its thread, and the rest of the document keeps the pool.
//!
//! The custom layout source lives on the frame's thread and carries no `Sync` bound, and the
//! umbrella application installs one whether or not the document holds a custom element. Batches
//! used to stay off for the whole pass because of it — which meant no real application ever
//! distributed a layout. What holds now: the distributor pins the subtrees that hold a custom
//! element to the frame's thread and hands everything else to the workers, so one code block in a
//! long document stops serialising the window.
//!
//! The counters are a process-wide block, so this is one test in a target of its own.

use std::sync::Arc;

use zgui_custom::{CustomElement, CustomLayoutCx, CustomMeasured, ScenePainter};
use zgui_geom::{Device, DevicePx, Size};
use zgui_platform::{Surface, SurfaceEvent};
use zgui_platform_headless::Harness;
use zgui_profile::{COUNTERS_ENABLED, Counter, counter};
use zgui_runtime::{App, AppError, Runtime};
use zgui_view::{Anchor, BuildCx, IntoView, View};

/// How many rows stand beside the custom element.
///
/// Enough that the resize relayout clears the distribution gates — eight cold subtrees, 256
/// planned boxes, eight items at the flex site — with the custom row pinned out of the count.
const ROWS: usize = 64;

/// A meter with a fixed answer, so the pinning claim has geometry to check.
struct Meter;

impl CustomElement for Meter {
    fn layout(&mut self, cx: &mut CustomLayoutCx<'_>) -> CustomMeasured {
        CustomMeasured {
            width: cx.known_width.unwrap_or(40.0),
            height: 24.0,
            ..CustomMeasured::default()
        }
    }

    fn paint(&mut self, painter: &mut ScenePainter<'_>) {
        let size = painter.size();
        painter.fill(
            zgui_geom::Rect::new(
                zgui_geom::Point::new(zgui_geom::DevicePx(0.0), zgui_geom::DevicePx(0.0)),
                size,
            ),
            0.0,
            painter.current_color(),
        );
    }
}

/// An application whose window records rather than draws, with the custom sources installed.
fn app<V>(css: &str, view: V) -> Harness<Runtime>
where
    V: FnMut(&mut BuildCx<'_>) -> Box<dyn Anchor> + 'static,
{
    let handler = App::new()
        .with_title("custom batches")
        .with_size(400.0, 300.0)
        .with_stylesheet(css)
        .with_renderer(Box::new(
            |_surface: &Arc<dyn Surface>, target| -> Result<_, AppError> {
                let mut renderer = zgui_testkit_scene::CaptureRenderer::new();
                zgui_render::Renderer::configure(&mut renderer, target);
                Ok(Box::new(renderer) as Box<dyn zgui_render::Renderer>)
            },
        ))
        .with_text_engine(Box::new(|| {
            Box::new(zgui_layout::Paragraphs::new(
                zgui_testkit_scene::MonoShaper::new(),
            ))
        }))
        .with_custom(Box::new(|_document| zgui_custom::sources()))
        .into_handler(view)
        .expect("the reactive runtime installs");
    Harness::new(handler)
}

/// A surface extent of `width` by a fixed height.
fn wide(width: f32) -> Size<DevicePx, Device> {
    Size::new(DevicePx(width), DevicePx(300.0))
}

/// The border box of the first box generated by an element named `name`.
fn box_of(window: &zgui_runtime::Window, name: &str) -> Option<(f32, f32, f32, f32)> {
    let document = window.document().borrow();
    let layout = window.layout().borrow();
    for key in layout.keys() {
        let node = layout.node(key);
        let Some(source) = node.source else {
            continue;
        };
        let Some(index) = document.store().index_of(source) else {
            continue;
        };
        if document.store().core(index).local_name().as_str() != name {
            continue;
        }
        let fragment = *layout.fragments_of_box(key).first()?;
        let fragment = layout.fragment(fragment)?;
        return Some((
            fragment.border_box.origin.x.0,
            fragment.border_box.origin.y.0,
            fragment.border_box.size.width.0,
            fragment.border_box.size.height.0,
        ));
    }
    None
}

#[test]
fn a_document_with_one_custom_element_still_distributes_its_batches() {
    if std::thread::available_parallelism().map_or(1, std::num::NonZeroUsize::get) < 2 {
        eprintln!("SKIPPED: one hardware thread, so no pool is ever installed");
        return;
    }

    let (view, _handle) = zgui_custom::custom(Meter);
    let mut harness = app(
        "root { display: flex; flex-direction: column; width: 100%; height: 100% }
         .row { display: block }
         text { display: block }",
        {
            let mut meter = Some(view);
            move |cx: &mut BuildCx<'_>| {
                let mut root = zgui_elements::column().class("root");
                for row in 0..ROWS {
                    // Five blocks per row, so the batch's planned boxes clear the 256-box floor
                    // with the row count the flex site needs.
                    let mut built = zgui_elements::r#box().class("row");
                    for line in 0..5 {
                        built = built.child(
                            zgui_elements::text()
                                .child(format!("row {row} line {line} carries a few words")),
                        );
                    }
                    root = root.child(built);
                }
                root = root.child(meter.take().expect("built once"));
                Box::new(root.into_view().build(cx))
            }
        },
    );
    harness.deliver_to_first(SurfaceEvent::Resized(wide(400.0)));
    harness.settle(64);
    // One resize before the measured one, so the step below is a drag in progress rather than
    // the first resize's one-time box rebuild.
    harness.deliver_to_first(SurfaceEvent::Resized(wide(440.0)));
    harness.settle(64);

    let before = counter::snapshot();
    harness.deliver_to_first(SurfaceEvent::Resized(wide(480.0)));
    harness.settle(64);
    let moved = before.delta(&counter::snapshot());

    let window = &harness.app().windows()[0];
    let meter = box_of(window, "custom").expect("the custom element laid out");
    assert_eq!(
        (meter.2, meter.3),
        (480.0, 24.0),
        "the pinned element still answers through the installed source at the new width"
    );

    if !COUNTERS_ENABLED {
        return;
    }
    assert!(
        moved.layout_batches_distributed > 0,
        "a resize of {ROWS} rows beside one custom element distributed no batch: the custom \
         source is serialising the whole pass again"
    );
    assert_eq!(
        moved.text_shaped, 0,
        "a warm width step shaped {} runs on the workers; shaping is width-independent, so the \
         batch handoff lost the shaped paragraphs it was meant to carry",
        moved.text_shaped
    );
}
