//! A custom element, through the real frame loop: measured by its trait, placing its own child.
//!
//! Everything here runs the pipeline a window runs — build, restyle, boxes, layout, fragments —
//! with the registry's sources installed the way the umbrella crate installs them. What is
//! asserted is the two halves of the contract: the element's `layout` answer is what CSS wraps
//! and layout keeps, and a child the element places lands exactly where it put it.

use std::sync::Arc;

use zgui_custom::{CustomElement, CustomLayoutCx, CustomMeasured, ScenePainter};
use zgui_platform::Surface;
use zgui_platform_headless::Harness;
use zgui_runtime::{App, AppError, Runtime};
use zgui_view::{Anchor, BuildCx, IntoView, View};

/// An application whose window records rather than draws, with the custom sources installed.
fn app<V>(css: &str, view: V) -> Harness<Runtime>
where
    V: FnMut(&mut BuildCx<'_>) -> Box<dyn Anchor> + 'static,
{
    let handler = App::new()
        .with_title("custom")
        .with_size(400.0, 300.0)
        .with_stylesheet(css)
        .with_renderer(Box::new(
            |_surface: &Arc<dyn Surface>, target| -> Result<_, AppError> {
                let mut renderer = zgui_testkit_scene::CaptureRenderer::new();
                zgui_render::Renderer::configure(&mut renderer, target);
                Ok(Box::new(renderer) as Box<dyn zgui_render::Renderer>)
            },
        ))
        .with_text_engine(Box::new(|| {
            Box::new(zgui_layout::Paragraphs::new(
                zgui_testkit_scene::MonoShaper::new(),
            ))
        }))
        .with_custom(Box::new(|_document| zgui_custom::sources()))
        .into_handler(view)
        .expect("the reactive runtime installs");
    Harness::new(handler)
}

/// A meter: fixed content size, and its one child parked at a corner of its own choosing.
struct Meter;

impl CustomElement for Meter {
    fn layout(&mut self, cx: &mut CustomLayoutCx<'_>) -> CustomMeasured {
        if cx.final_pass && cx.access.child_count() > 0 {
            cx.access.layout_child(
                0,
                (Some(10.0), Some(6.0)),
                (
                    zgui_custom::Space::Definite(10.0),
                    zgui_custom::Space::Definite(6.0),
                ),
            );
            cx.access.place_child(0, 5.0, 7.0);
        }
        CustomMeasured {
            width: cx.known_width.unwrap_or(40.0),
            height: 24.0,
            ..CustomMeasured::default()
        }
    }

    fn paint(&mut self, painter: &mut ScenePainter<'_>) {
        let size = painter.size();
        painter.fill(
            zgui_geom::Rect::new(
                zgui_geom::Point::new(zgui_geom::DevicePx(0.0), zgui_geom::DevicePx(0.0)),
                size,
            ),
            3.0,
            painter.current_color(),
        );
    }
}

/// The border box of the first box generated by an element named `name`.
fn box_of(window: &zgui_runtime::Window, name: &str) -> Option<(f32, f32, f32, f32)> {
    let document = window.document().borrow();
    let layout = window.layout().borrow();
    for key in layout.keys() {
        let node = layout.node(key);
        let Some(source) = node.source else {
            continue;
        };
        let Some(index) = document.store().index_of(source) else {
            continue;
        };
        if document.store().core(index).local_name().as_str() != name {
            continue;
        }
        let fragment = layout.fragments_of_box(key).first()?;
        let fragment = layout.fragment(*fragment)?;
        return Some((
            fragment.border_box.origin.x.0,
            fragment.border_box.origin.y.0,
            fragment.border_box.size.width.0,
            fragment.border_box.size.height.0,
        ));
    }
    None
}

#[test]
fn a_custom_element_is_measured_by_its_trait_and_places_its_child() {
    let (view, _handle) = zgui_custom::custom(Meter);
    let mut app = app(
        "root { display: block; width: 400px; height: 300px }
         item { display: block }",
        {
            let mut view = Some(view.child(zgui_elements::Element::<Item>::new()));
            move |cx: &mut BuildCx<'_>| {
                Box::new(
                    zgui_elements::r#box()
                        .class("root")
                        .child(view.take().expect("built once"))
                        .into_view()
                        .build(cx),
                )
            }
        },
    );
    app.settle(16);

    let window = &app.app_mut().windows_mut()[0];
    let custom = box_of(window, "custom").expect("the custom element laid out");
    assert_eq!(
        (custom.2, custom.3),
        (400.0, 24.0),
        "block flow stretched the width the shell offered; the height is the element's own answer"
    );
    let item = box_of(window, "item").expect("the child laid out");
    assert_eq!(
        (item.0 - custom.0, item.1 - custom.1),
        (5.0, 7.0),
        "the child sits exactly where the element placed it, relative to the element's box"
    );
    assert_eq!(
        (item.2, item.3),
        (10.0, 6.0),
        "at the size the element laid it out at"
    );
}

/// The custom child's tag, for the fixture: any name will do, the element places by index.
struct Item;

impl zgui_elements::tag::Tag for Item {
    fn name() -> zgui_interned::ElementName {
        zgui_interned::ElementName::new("item")
    }
}
